import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        vermelho: '#d42b2b',
        surface: 'var(--surface)',
        'surface-dim': 'var(--surface-dim)',
        card: 'var(--card)',
        'card-hi': 'var(--card-hi)',
        line: 'var(--line)',
        'line-hi': 'var(--line-hi)',
        ink: 'var(--ink)',
        dim: 'var(--dim)',
        faint: 'var(--faint)',
        // ── Admin — tokens de tema (trocam via [data-admin-theme]) ──
        'brand-bg':            'var(--brand-bg)',
        'brand-sidebar':       'var(--brand-sidebar)',
        'brand-surface':       'var(--brand-surface)',
        'brand-surface-2':     'var(--brand-surface-2)',
        'brand-elevated':      'var(--brand-elevated)',
        'brand-hair':          'var(--brand-hair)',
        'brand-border':        'var(--brand-border)',
        'brand-border-strong': 'var(--brand-border-strong)',
        'brand-text':          'var(--brand-text)',
        'brand-muted':         'var(--brand-muted)',
        'brand-dim':           'var(--brand-dim)',
        'brand-accent':        'var(--brand-accent)',
        'brand-accent-hover':  'var(--brand-accent-hover)',
        'brand-accent-soft':   'var(--brand-accent-soft)',
        'brand-on-accent':      'var(--brand-on-accent)',
        'brand-on-accent-soft': 'var(--brand-on-accent-soft)',
        'brand-success':       'var(--brand-success)',
        'brand-success-soft':  'var(--brand-success-soft)',
        'brand-warning':       'var(--brand-warning)',
        'brand-warning-soft':  'var(--brand-warning-soft)',
        'brand-danger':        'var(--brand-danger)',
        'brand-danger-soft':   'var(--brand-danger-soft)',
        'brand-info':          'var(--brand-info)',
        'brand-info-soft':     'var(--brand-info-soft)',
        'brand-neutral-soft':  'var(--brand-neutral-soft)',
        'brand-tint-1':        'var(--brand-tint-1)',
        'brand-tint-2':        'var(--brand-tint-2)',
        'brand-tint-3':        'var(--brand-tint-3)',
      },
      boxShadow: {
        card: 'var(--brand-shadow-card)',
        pop:  'var(--brand-shadow-pop)',
        cta:  'var(--brand-shadow-cta)',
      },
      ringColor: {
        'brand-accent': 'var(--brand-accent-ring)',
      },
      fontFamily: {
        barlow: ['var(--font-barlow)', 'Barlow Condensed', 'sans-serif'],
        inter: ['var(--font-inter)', 'Inter', 'sans-serif'],
        // Legacy aliases used in admin and shared components
        rajdhani: ['var(--font-barlow)', 'sans-serif'],
        outfit: ['var(--font-inter)', 'sans-serif'],
        grotesk: ['var(--font-barlow)', 'sans-serif'],
        mono: ['monospace'],
      },
      borderRadius: {
        DEFAULT: '4px',
        sm: '3px',
        md: '4px',
        lg: '6px',
        xl: '6px',
        '2xl': '8px',
      },
      backgroundImage: {
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
      },
    },
  },
  plugins: [],
}
export default config
