'use client'

import Link from 'next/link'
import { ChangeEvent, useState } from 'react'
import { Camera, Download, ExternalLink, FileQuestion, Gift, QrCode, Save, Users } from 'lucide-react'

export function AdminEventoPirelli({ evento: inicial, qrs }: { evento: any; qrs: { titulo: string; descricao: string; url: string; svg: string }[] }) {
  const [evento, setEvento] = useState(inicial); const [mensagem, setMensagem] = useState(''); const [salvando, setSalvando] = useState(false)
  async function salvar() { setSalvando(true); const resposta = await fetch('/api/admin/evento-pirelli', { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(evento) }); const dados = await resposta.json(); setSalvando(false); if (resposta.ok) { setEvento({ ...dados, dataInicio: dados.dataInicio ? new Date(dados.dataInicio).toISOString().slice(0, 16) : null, dataFim: dados.dataFim ? new Date(dados.dataFim).toISOString().slice(0, 16) : null, valorMinimoPneus: Number(dados.valorMinimoPneus) }); setMensagem('Configuração salva.') } else setMensagem(dados.error) }
  async function upload(campo: string, event: ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; if (!file) return; setMensagem('Enviando imagem…'); const fd = new FormData(); fd.append('file', file); fd.append('pasta', 'evento-pirelli'); const resposta = await fetch('/api/upload', { method: 'POST', body: fd }); const dados = await resposta.json(); if (resposta.ok) { setEvento({ ...evento, [campo]: dados.url }); setMensagem('Imagem enviada. Clique em salvar para publicar.') } else setMensagem(dados.error) }
  return <div className="max-w-6xl mx-auto space-y-6 pb-20">
    <header className="flex flex-wrap justify-between gap-4"><div><p className="text-brand-accent text-xs font-bold uppercase tracking-widest">Operação de stand</p><h1 className="font-barlow font-black text-4xl text-brand-text">Evento Pirelli</h1><p className="text-brand-muted mt-1">Ferramentas diretas, pensadas para atendimento em fila.</p></div><a href="/evento-pirelli" target="_blank" className="inline-flex h-fit gap-2 items-center rounded-xl border border-brand-border px-4 py-3 text-brand-text"><ExternalLink size={16}/> Abrir landing</a></header>
    <nav className="grid grid-cols-2 md:grid-cols-5 gap-3">{[[ '/admin/evento-pirelli/atendimento', 'Atendimento', Users ], ['/admin/evento-pirelli/leads', 'Leads', Users], ['/admin/evento-pirelli/canecas', 'Canecas', Gift], ['/admin/evento-pirelli/fotos', 'Fotos', Camera], ['/admin/evento-pirelli/quiz', 'Quiz', FileQuestion]].map(([href, label, Icon]: any) => <Link key={href} href={href} className="rounded-2xl p-5 bg-brand-surface border border-brand-border text-brand-text hover:border-brand-accent flex gap-3 items-center"><Icon className="text-brand-accent"/><b>{label}</b></Link>)}</nav>
    <section className="rounded-2xl bg-brand-surface border border-brand-border p-5"><h2 className="font-barlow text-2xl font-black text-brand-text mb-4">QR codes para imprimir</h2><div className="grid md:grid-cols-3 gap-4">{qrs.map((qr) => <div key={qr.titulo} className="bg-white text-[#111] rounded-xl p-4 text-center"><div className="mx-auto w-[180px] h-[180px]" dangerouslySetInnerHTML={{ __html: qr.svg }}/><b className="block mt-2">{qr.titulo}</b><p className="text-xs text-[#666] min-h-8">{qr.descricao}</p><button onClick={() => window.print()} className="mt-3 text-sm inline-flex gap-1 items-center text-[#d42b2b]"><QrCode size={14}/> Imprimir esta página</button></div>)}</div></section>
    <section className="rounded-2xl bg-brand-surface border border-brand-border p-5"><h2 className="font-barlow text-2xl font-black text-brand-text mb-4">Configuração da landing e promoção</h2><div className="grid md:grid-cols-2 gap-4">{[['titulo','Título'],['local','Local'],['descricao','Copy de apresentação'],['logoForzaUrl','Logo Forza (URL)'],['logoPirelliUrl','Logo Pirelli (URL)'],['logoCampneusUrl','Logo Campneus (URL)']].map(([campo, label]) => <label className="text-sm text-brand-muted" key={campo}>{label}<input value={evento[campo] ?? ''} onChange={(e) => setEvento({ ...evento, [campo]: e.target.value })} className="mt-1 block w-full rounded-lg bg-black/20 border border-brand-border p-3 text-brand-text" /></label>)}
        <label className="text-sm text-brand-muted">Início<input type="datetime-local" value={evento.dataInicio ? evento.dataInicio.slice(0,16) : ''} onChange={(e) => setEvento({ ...evento, dataInicio: e.target.value })} className="mt-1 block w-full rounded-lg bg-black/20 border border-brand-border p-3 text-brand-text" /></label><label className="text-sm text-brand-muted">Fim<input type="datetime-local" value={evento.dataFim ? evento.dataFim.slice(0,16) : ''} onChange={(e) => setEvento({ ...evento, dataFim: e.target.value })} className="mt-1 block w-full rounded-lg bg-black/20 border border-brand-border p-3 text-brand-text" /></label>
        <label className="text-sm text-brand-muted">Limite do nome de gravação<input type="number" min="2" max="50" value={evento.limiteNomeGravacao} onChange={(e) => setEvento({ ...evento, limiteNomeGravacao: Number(e.target.value) })} className="mt-1 block w-full rounded-lg bg-black/20 border border-brand-border p-3 text-brand-text" /></label><label className="text-sm text-brand-muted">Subtotal de pneus (R$)<input type="number" min="0" step="0.01" value={evento.valorMinimoPneus} onChange={(e) => setEvento({ ...evento, valorMinimoPneus: Number(e.target.value) })} className="mt-1 block w-full rounded-lg bg-black/20 border border-brand-border p-3 text-brand-text" /></label>
        <label className="text-sm text-brand-muted">Operador<select value={evento.operadorValorMinimoPneus} onChange={(e) => setEvento({ ...evento, operadorValorMinimoPneus: e.target.value })} className="mt-1 block w-full rounded-lg bg-black/20 border border-brand-border p-3 text-brand-text"><option value="MAIOR_QUE">Maior que (&gt;)</option><option value="MAIOR_OU_IGUAL">Maior ou igual (≥)</option></select></label>
        {['logoForzaUrl','logoPirelliUrl','logoCampneusUrl'].map((campo) => <label key={campo} className="text-sm text-brand-muted">Enviar {campo.replace('Url','')}<input type="file" accept="image/*" onChange={(e) => upload(campo, e)} className="mt-1 block w-full text-xs"/></label>)}
      </div><div className="flex gap-4 mt-5"><label className="text-sm text-brand-text flex gap-2"><input type="checkbox" checked={evento.ativo} onChange={(e) => setEvento({ ...evento, ativo: e.target.checked })}/> Ativo</label><label className="text-sm text-brand-text flex gap-2"><input type="checkbox" checked={evento.publicado} onChange={(e) => setEvento({ ...evento, publicado: e.target.checked })}/> Publicado</label></div>{mensagem && <p className="mt-3 text-sm text-brand-muted">{mensagem}</p>}<button onClick={salvar} disabled={salvando} className="mt-5 inline-flex gap-2 rounded-xl bg-brand-accent px-5 py-3 text-white font-bold"><Save size={16}/>{salvando ? 'Salvando…' : 'Salvar configurações'}</button></section>
    <section className="rounded-2xl bg-brand-surface border border-brand-border p-5"><h2 className="font-barlow text-2xl font-black text-brand-text">Exportações</h2><div className="flex flex-wrap gap-3 mt-3">{['leads','quiz','canecas','fotos','compras'].map((tipo) => <a key={tipo} href={`/api/admin/evento-pirelli/export?tipo=${tipo}`} className="inline-flex gap-2 border border-brand-border text-brand-text rounded-xl px-4 py-3"><Download size={16}/> CSV {tipo}</a>)}</div></section>
  </div>
}
